# Thông tin cá nhân
title: Phan Anh | AI & Data Science Portfolio
author: Phan Anh
description: Trang web cá nhân giới thiệu các dự án Nghiên cứu & Phát triển trong lĩnh vực Trí tuệ nhân tạo.

# Cấu hình Giao diện (Theme)
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# Đường dẫn liên kết mạng xã hội (Theme Minimal hỗ trợ sẵn ở sidebar)
github_username: kizzzbk # Đổi thành tên tài khoản GitHub thật của bạn

# Cấu hình hiển thị công thức toán học nếu cần
markdown: kramdown
kramdown:
  math_engine: mathjax